### ISSUE TITLE
Bug saat gelbooru tipenya video

### ISSUE THREAD

**Issue by royu43** [ChocoRin43/anon-dan-renbot#1]
di discord
![problem the video gelbooru](https://github.com/user-attachments/assets/84d284c2-51d3-4611-a9e4-a0b827034b0d)

namun di sumbernya video
![2](https://github.com/user-attachments/assets/11266522-c833-4932-8561-44029b0591e7)

**Comment by ChocoRin43** [comment]
bego malah di close wwkwk

**Comment by ChocoRin43** [comment]
besok kayanya baru di fix

**Comment by ChocoRin43** [comment]
update, gw baru tau ternyata nonton di discordnya langsung ngga bisa wkwkwk, ama gw ganti jadi prev aja, nontonya di sumbernya aja, jadi ama gw kasih previewnya

**Comment by ChocoRin43** [comment]
Beres, jadi jika file tersebut mengandung video akan diarahkan ke link untuk menonton dan fotonya akan dijadikan preview
